// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucecslbwzqjtmuvvnisq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZWNzbGJ3enFqdG11dnZuaXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2MTA5MjEsImV4cCI6MjA4MzE4NjkyMX0.huPCtPg4SqCj_8KbTQKVB5aDwwmvL96PZYfzA1Qw4Qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});